general {
    lock_cmd = hyprlock --config ~/.config/hypr/hyprlock/hyprlock.conf
    before_sleep_cmd = hyprlock --config ~/.config/hypr/hyprlock/hyprlock.conf
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 30 # 5 minutes
    on_timeout = hyprlock
}

listener {
    timeout = 600 # 10 minutes
    on_timeout = hyprctl dispatch dpms off
    on_resume = hyprctl dispatch dpms on
}
