# Import Catppuccin Mocha theme
source = $HOME/.config/hypr/mocha.conf

# Define accent colors and font
$accent = $mauve
$accentAlpha = $mauveAlpha
$font = JetBrainsMono Nerd Font

# GENERAL SETTINGS
general {
  hide_cursor = true
}

# BACKGROUND SETTINGS
background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 10
    noise = 0.02
    contrast = 0.9
    brightness = 0.8
    vibrancy = 0.2
    vibrancy_darkness = 0.0
}

# TIME LABEL
label {
  monitor =
  text = cmd[update:1000] date +"%H:%M:%S"
  color = $text
  font_size = 90
  font_family = $font
  position = -30, 0
  halign = right
  valign = top
}

# DATE LABEL
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = 25
  font_family = $font
  position = -30, -150
  halign = right
  valign = top
}

# MEDIA WIDGET
# label {
#   monitor =
#   text = cmd[update:1000] playerctl metadata --format "{{ artist }} - {{ title }}"
#   color = $text
#   font_size = 20
#   font_family = $font
#   position = 0, 150
#   halign = center
#   valign = center
# }

# BATTERY WIDGET
label {
  monitor =
  text = cmd[update:60000] echo "Battery: $(cat /sys/class/power_supply/BAT1/capacity)%"
  color = $text
  font_size = 20
  font_family = $font
  position = 0, 200
  halign = center
  valign = center
}

# USER AVATAR
image {
  monitor =
  path = $HOME/.face
  size = 100
  border_color = $accent
  position = 0, 75
  halign = center
  valign = center
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $surface0
  font_color = $text
  fade_on_empty = false
  placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -47
  halign = center
  valign = center
}

